from typing import List, Dict, Optional, Any
from pydantic import BaseModel, Field

class DataFramePresentationPlan(BaseModel):
    """
    Plan for how to present the DataFrame to the user.
    Generated by LLM based on user query and available columns.
    """
    keep_columns: List[str] = Field(..., description="List of column names to display in the final table. MUST be selected from the available columns.")
    rename_map: Optional[Dict[str, str]] = Field(None, description="Dictionary mapping original column names to user-friendly display names. e.g. {'budget_sum': '總預算'}")
    sort_by: Optional[str] = Field(None, description="Column name to sort by.")
    sort_order: Optional[str] = Field("desc", description="Sort order: 'asc' or 'desc'. Default is 'desc'.")
    limit: Optional[int] = Field(20, description="Number of rows to display. Default is 20.")
    rationale: str = Field(..., description="Brief reason why these columns and sorting were chosen.")
